require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScheduleRatesController do

  # This should return the minimal set of attributes required to create a valid
  # ScheduleRate. As you add validations to ScheduleRate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScheduleRatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all schedule_rates as @schedule_rates" do
      schedule_rate = ScheduleRate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:schedule_rates).should eq([schedule_rate])
    end
  end

  describe "GET show" do
    it "assigns the requested schedule_rate as @schedule_rate" do
      schedule_rate = ScheduleRate.create! valid_attributes
      get :show, {:id => schedule_rate.to_param}, valid_session
      assigns(:schedule_rate).should eq(schedule_rate)
    end
  end

  describe "GET new" do
    it "assigns a new schedule_rate as @schedule_rate" do
      get :new, {}, valid_session
      assigns(:schedule_rate).should be_a_new(ScheduleRate)
    end
  end

  describe "GET edit" do
    it "assigns the requested schedule_rate as @schedule_rate" do
      schedule_rate = ScheduleRate.create! valid_attributes
      get :edit, {:id => schedule_rate.to_param}, valid_session
      assigns(:schedule_rate).should eq(schedule_rate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScheduleRate" do
        expect {
          post :create, {:schedule_rate => valid_attributes}, valid_session
        }.to change(ScheduleRate, :count).by(1)
      end

      it "assigns a newly created schedule_rate as @schedule_rate" do
        post :create, {:schedule_rate => valid_attributes}, valid_session
        assigns(:schedule_rate).should be_a(ScheduleRate)
        assigns(:schedule_rate).should be_persisted
      end

      it "redirects to the created schedule_rate" do
        post :create, {:schedule_rate => valid_attributes}, valid_session
        response.should redirect_to(ScheduleRate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved schedule_rate as @schedule_rate" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduleRate.any_instance.stub(:save).and_return(false)
        post :create, {:schedule_rate => {}}, valid_session
        assigns(:schedule_rate).should be_a_new(ScheduleRate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduleRate.any_instance.stub(:save).and_return(false)
        post :create, {:schedule_rate => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested schedule_rate" do
        schedule_rate = ScheduleRate.create! valid_attributes
        # Assuming there are no other schedule_rates in the database, this
        # specifies that the ScheduleRate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScheduleRate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => schedule_rate.to_param, :schedule_rate => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested schedule_rate as @schedule_rate" do
        schedule_rate = ScheduleRate.create! valid_attributes
        put :update, {:id => schedule_rate.to_param, :schedule_rate => valid_attributes}, valid_session
        assigns(:schedule_rate).should eq(schedule_rate)
      end

      it "redirects to the schedule_rate" do
        schedule_rate = ScheduleRate.create! valid_attributes
        put :update, {:id => schedule_rate.to_param, :schedule_rate => valid_attributes}, valid_session
        response.should redirect_to(schedule_rate)
      end
    end

    describe "with invalid params" do
      it "assigns the schedule_rate as @schedule_rate" do
        schedule_rate = ScheduleRate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduleRate.any_instance.stub(:save).and_return(false)
        put :update, {:id => schedule_rate.to_param, :schedule_rate => {}}, valid_session
        assigns(:schedule_rate).should eq(schedule_rate)
      end

      it "re-renders the 'edit' template" do
        schedule_rate = ScheduleRate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduleRate.any_instance.stub(:save).and_return(false)
        put :update, {:id => schedule_rate.to_param, :schedule_rate => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested schedule_rate" do
      schedule_rate = ScheduleRate.create! valid_attributes
      expect {
        delete :destroy, {:id => schedule_rate.to_param}, valid_session
      }.to change(ScheduleRate, :count).by(-1)
    end

    it "redirects to the schedule_rates list" do
      schedule_rate = ScheduleRate.create! valid_attributes
      delete :destroy, {:id => schedule_rate.to_param}, valid_session
      response.should redirect_to(schedule_rates_url)
    end
  end

end
